timothy = User.create!(username: 'Timothy')
joaquin = User.create!(username: 'Joaquin')
nicolas = User.create!(username: 'Nicolas')
sebastian = User.create!(username: 'Sebastian')
PaymentAccount.create!(user: timothy, balance: 500)
PaymentAccount.create!(user: joaquin, balance: 344.50)
PaymentAccount.create!(user: nicolas, balance: 850)
PaymentAccount.create!(user: sebastian, balance: 120)
ExternalPaymentSource.create!(user: timothy)
ExternalPaymentSource.create!(user: joaquin)
ExternalPaymentSource.create!(user: nicolas)
ExternalPaymentSource.create!(user: sebastian)
Friendship.create!(first_friend: timothy, second_friend: joaquin)
Friendship.create!(first_friend: joaquin, second_friend: nicolas)
Friendship.create!(first_friend: nicolas, second_friend: sebastian)
